### ISSUE TITLE
Unable to Pull New Version from Jitpack

### ISSUE THREAD

**Issue by hanserya** [alturkovic/distributed-lock#13]
Thanks for certifying the project on the latest version of the Spring Boot framework. Unfortunately, I am unable to pull the latest version for any of the packages. If I try to pull the following as specified by Jitpack, then I get an auth error.

```
<dependency>
    <groupId>com.github.alturkovic</groupId>
    <artifactId>distributed-lock</artifactId>
    <version>1.3.0</version>
</dependency>
```

I am still able to pull 1.2.2 without issue.

**Comment by alturkovic** [comment]
Yeah, my bad, JitPack was trying to build with 1.8 and I upgraded to java 11. 
I decided to revert to java 1.8 instead of using 11 since many projects still do not use it so 1.4.0 should now work properly.
https://jitpack.io/com/github/alturkovic/distributed-lock/1.4.0/build.log
