### ISSUE TITLE
1.3.0 build failing in jitpack

### ISSUE THREAD

**Issue by molexx** [alturkovic/distributed-lock#15]
https://jitpack.io/com/github/alturkovic/distributed-lock/1.3.0/build.log

**Comment by alturkovic** [comment]
Yeah, my bad, JitPack was trying to build with 1.8 and I upgraded to java 11. 
I decided to revert to java 1.8 instead of using 11 since many projects still do not use it so 1.4.0 should now work properly.
https://jitpack.io/com/github/alturkovic/distributed-lock/1.4.0/build.log

**Comment by molexx** [comment]
Thanks!

Great lib btw, just works. Very helpful!

**Comment by alturkovic** [comment]
Thank you :)
