### ISSUE TITLE
MongoLocked: Don't retry on "fail to acquire"

### ISSUE THREAD

**Issue by luccasmf** [alturkovic/distributed-lock#27]
Is there a way to set the Lock to not retry ?

**Comment by alturkovic** [comment]
I did not test it, I am a bit overwhelmed at the moment, but I think if you set retry period to longer than the timeout period, it should do the trick?

**Comment by alturkovic** [comment]
I added a new support to disable retries when it is defined as `retry = @Interval("0")`
