### ISSUE TITLE
Null lock token versus LockNotAvailableException

### ISSUE THREAD

**Issue by PunchyRascal** [alturkovic/distributed-lock#33]
Hi, 

when acquiring a lock (manually), there seems to be some confusion as to what should happen when the lock is not acquired.

The documentation on the Lock interface states, that null will be returned from acquire(), but both implementations seem to be throwing an exception (LockNotAvailableException).

So I am not sure what to do: If I rely in the interface, my code will fail. If I rely on the implementation, it may change and fail, just in reverse.

Am I missing something?

**Comment by alturkovic** [comment]
> The documentation on the Lock interface states, that null will be returned from acquire(), but both implementations seem to be throwing an exception (LockNotAvailableException).

Could you be more specific, which implementations are you talking about? I see that all `AbstractSimpleLock` implementations return `null`, as well as `MultiRedisLock` do not throw that exception.

**Comment by PunchyRascal** [comment]
I am using JDBC, but I think it's the retriable lock that does this: 
https://github.com/alturkovic/distributed-lock/blob/21d3a55e6830eed0a5b36877c8f65c5e8f2b39be/distributed-lock-core/src/main/java/com/github/alturkovic/lock/retry/RetriableLock.java#L49

**Comment by PunchyRascal** [comment]
Thanks!
