### ISSUE TITLE
"RetriableLock should return null if lock is not acquired after the last retry" - ok.. but why?

### ISSUE THREAD

**Issue by PsychoThinker** [alturkovic/distributed-lock#35]
It seemed to me that the main purpose of the @Locked annotation was to prevent a method from being executing if the previous call to it had not yet finished.

And after this change, acquire lock will be retried until finally a null token is returned instead of an exception being thrown (consequently the annotated method will be called as if lock were not there).

**Comment by alturkovic** [comment]
It was implemented to handle manual locking: https://github.com/alturkovic/distributed-lock/issues/33

I have added a fix to execute locked methods over AOP only if token is acquired. That should solve both use-cases. Please try the new version and let me know.

**Comment by PsychoThinker** [comment]
Yes, now it works as expected. Thank you very much for the quick fix!
