### ISSUE TITLE
Importing the whole library causes auto wiring issues in Spring Boot

### ISSUE THREAD

**Issue by davegray-news** [alturkovic/distributed-lock#38]
**The Problem**
Using one of the out-of-the-box lock implementations, e.g. JDBC, BUT importing the whole library as per the readme, i.e.
```maven
<dependencies>
  <dependency>
    <groupId>com.github.alturkovic.distributed-lock</groupId>
    <artifactId>distributed-lock-redis</artifactId>
    <version>[insert latest version here]</version>
  </dependency>
</dependencies>
```
causes Spring Boot auto wiring issues during startup for the other implementations, e.g.1
```
"Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface uk.co.news.applenews.respository.AppleNewsFailedReceiptRepository. If you want this repository to be a MongoDB repository, consider annotating your entities with one of these annotations: org.springframework.data.mongodb.core.mapping.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.mongodb.repository.MongoRepository."
```
and e.g.2
```
"Spring Data Redis - Could not safely identify store assignment for repository candidate interface uk.co.news.applenews.respository.AppleNewsFailedReceiptRepository. If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository."
```

**Suggested Solution**
Exclude the out-of-the-box lock implementations that aren't needed, e.g.
```gradle
    implementation('com.github.alturkovic:distributed-lock:1.5.5'){
        exclude module: 'distributed-lock-example'
        exclude module: 'distributed-lock-mongo'
        exclude module: 'distributed-lock-redis'
    }
```

**Comment by alturkovic** [comment]
They are already organized that way? You should not include `com.github.alturkovic:distributed-lock:1.5.5` but `com.github.alturkovic:distributed-lock-redis:1.5.5` or `com.github.alturkovic:distributed-lock-jdbc:1.5.5`

**Comment by davegray-news** [comment]
Fair enough - so I think the readme should say that.

**Comment by alturkovic** [comment]
The README says the following:

> JitPack builds multi-modules by appending the repo name in the groupId. To add the Redis dependency for an example, add the following under your <dependencies>

Which part do you feel is not clear enough and needs more explanation? Can you propose a specific change?

**Comment by davegray-news** [comment]
Oh yes I see what you mean. I'm sorry - I misread the import (I think because it's Maven and not Gradle).
Probably doesn't need a update. Or maybe just add a Gradle example.

**Comment by alturkovic** [comment]
I'll see about the gradle example, but I will close this issue.
