### ISSUE TITLE
Does it Support Spring Boot 3 ?

### ISSUE THREAD

**Issue by terenceyeoh** [alturkovic/distributed-lock#39]
Hi , can i know does any release version to support Spring Boot 3 ?

**Comment by alturkovic** [comment]
Not yet since there was no interest, but I'll see what I can do when I get some spare time to work on this 👍

**Comment by PunchyRascal** [comment]
Just here to register my interest, too 🙂

**Comment by alturkovic** [comment]
> I spent working on the upgrade today! 🤣 I did able to upgrade except having trouble configuring redis. 😌

Spring Boot 3 now configures redis with `spring.data.redis` instead of `spring.redis` properties, maybe it is due to that change?

**Comment by jamilxt** [comment]
No, I was more focused on keeping your used libraries for testcontainers from playtika. I thought of using org.testcontainers but ignored it for some reason. 😅

Though I did able to run the MongoDB tests keeping the de.flapdoodle.embed dependency.

**Comment by alturkovic** [comment]
It seems to be working as expected to me. Closing this issue.
