### ISSUE TITLE
More detailed examples

### ISSUE THREAD

**Issue by AndreaAdvanon** [alturkovic/distributed-lock#4]
I'm trying to lock a couple of methods across jvm instances using Jdbc and Postgres.

So what I'm doing:
- `@EnableJdbcDistributedLock`
- creating the `lock` table:
```sql
CREATE TABLE lock
(
  id SERIAL,
  key VARCHAR(255) UNIQUE,
  token VARCHAR(255),
  expireAt TIMESTAMP
);
```
- annotating my method with `@JdbcLocked`

But it doesn't work: `Unable to acquire lock with expression: #executionPath`.

I'd like to use simply the name of the method as a key, for start.
But I'm not really sure how to move from here :sweat_smile:

**Comment by AndreaAdvanon** [comment]
Could `"DELETE FROM %s WHERE `expireAt` < ?;"` be the reason?
` are not part of the SQL standard and seems to be used by MySQL.

**Comment by AndreaAdvanon** [comment]
Yes, this is what I'd suggest. Unfortunately for the time being I would still require support for Spring Boot 1.*. Would you release a `1.1.6.1` version with this fix?

**Comment by alturkovic** [comment]
I didn't plan to support 1.X anymore, but I'll see what I can do when I get to my PC later.

**Comment by AndreaAdvanon** [comment]
It works, thanks!
