### ISSUE TITLE
JDBC Manual Controlled Lock

### ISSUE THREAD

**Issue by terenceyeoh** [alturkovic/distributed-lock#43]
Hi @alturkovic , 

Want to ask regarding the manually controlled locks, i saw the sample code as below but the method lock.acquire(keys, storeId, expiration, retry, timeout) is missing. I cant find acquire method with 5 params. Is it missing method on it ? 

And May i know does it possible have dedicated method to check whether it is locked instead of use the lock.acquired method to check on return token value whether it is empty ? Appreciate your help. Thanks

@Component
public class Example {

    @Autowired
    @Qualifier("simpleRedisLock")
    private Lock lock;

    // other fields...

    private void manuallyLocked() {
        // code before locking...

        final String token = lock.acquire(keys, storeId, expiration, retry, timeout);

        // check if you acquired a token
        if (StringUtils.isEmpty(token)) {
            throw new IllegalStateException("Lock not acquired!");
        }

        // code after locking...

        lock.release(keys, token, storeId);

        // code after releasing the lock...
    }
}

**Comment by alturkovic** [comment]
I updated the README, thanks for pointing that out. You should use `public String acquire(final List<String> keys, final String storeId, final long expiration)` method to manually acquire locks. 

There is no method for checking if lock is currently locked or not. What would be the use-case? If you had any kind of a logic depending on if it is locked or not, you would still need to acquire the lock first or you would run into race conditions.

If you do not acquire the lock, for an example with a `isLocked` method as you suggested, this is a simple example of a race condition:

```java
if (!lock.isLocked(keys, storeId) {
  // when this line executes, someone else might have acquired the lock since this if block would not be atomic and you would have a race condition
}
```

**Comment by alturkovic** [comment]
For manual retries, you can wrap your injected `lock` with a `RetriableLock` and add any kind of retriable behaviour you want. Take a look [here](distributed-lock-core/src/main/java/com/github/alturkovic/lock/retry/RetriableLock.java).

> Regarding the use-case, i want to display the status of key (Either lock or not lock) in UI. So, it is good if it has a dedicated method to check on the status so i not required to acquire a lock and release it immediately just to check the status of key.

I see... I'll see what I can do when I get some time to work on this, but, no promises... If you are in a hurry, feel free to open a PR and I'll gladly take a look.

**Comment by alturkovic** [comment]
I decided not to implement this since it is very specific and not the intended purpose of this library. 
I suggest you create your own `Lock` implementation and add such method yourself, it should be very straightforward.

If this issue gets more attention, I will reconsider it.
