### ISSUE TITLE
Testing Annotated Locks

### ISSUE THREAD

**Issue by Fraser-Cumming** [alturkovic/distributed-lock#44]
Hi,

I'm struggling to test the annotated locks. I've tried everything under the sun to get it to work but I cannot seem to get anything working.

It doesn't seem the annotation is working what so ever under test conditions (as evidenced by the fact, even when changing the storeId to one that doesn't exist nothing happens).

I've tried annotating the test class with `@EnableJdbcDistributedLock` even though my Application file already has this annotation. When the method is called it is not triggering the annotation at all.

I've tried annotating the method that I would like locked with both `@Locked` and `@JdbcLocked` of which neither made any difference.

I tried to create a very simple test to remove any doubt:

```java
    @JdbcLocked(expression = "#p0")
    public void fakeMethod(UUID id) {
        log.debug("Fake method called! {}", id);
    }
```

```java
    @Test
    public void simpleTest() {
        testService.fakeMethod(UUID.randomUUID());
    }
```

This should fail, since I don't even have a DB table available for this lock, yet it is not doing anything.

Any advice for testing the annotations would be greatly appreciated.

Spring Boot version 3.1.9 (tested with 3.1.5 too just in case)
Distributed Lock Version: `'com.github.alturkovic.distributed-lock:distributed-lock-jdbc:2.1.0'`

**Comment by Fraser-Cumming** [comment]
Okay I have made some progress, it seems that it was simply due to the fact that the annotated method **MUST** be autowired/created via bean. Which allows the annotation/proxy interceptors to work. Might be something to improve in the documentation, although it seems obvious in hindsight.

However I still have a question on testing the locks. I was creating two simple tests, one that simply calls the method and expects it to work, and then a second test that inserts a row into the lock table and then attempts to call the locked method (and expects it to fail).

Currently when manually inserting I am just simply putting either `null` or `UUID.randomUUID()` into the `token` field. I am not sure how this field works, so I am not sure how to mock this properly. 

I would expect by using a random or null token, I might not be properly testing the locking mechanism, because it may fail to find the token (Hence me getting errors about a token in the test), rather than it testing if there is a active lock currently would be great to have a bit of advice on this, thanks!

**Comment by alturkovic** [comment]
Yes, the locking mechanism works only for Spring beans, I will make a note of it in the README, thanks for pointing that out.

The `token` field is used to determine the lock owner. Imagine the following scenario: Service A acquires lock L with token TA. The service does some long processing and tries to hold the lock L for too long and the lock gets automatically released. This mechanism ensures that locks wont hang in case services break. The services acquiring the locks need to finish processing before the lock expires or refresh the lock while they hold it. Let's assume that the service holds it for too long and the lock gets released. Now, Service B acquires lock L with token TB. Service A completes its job and tries to release the lock L with token TA. That release will fail because the lock is now locked using token TB and can only be released using token TB.

For your testing purposes, I suggest sticking with a random UUID since that would represent that another service acquired the lock and your test does not own or know the value of that token, just like it would behave in production.

Hope that helps!

**Comment by Fraser-Cumming** [comment]
Thanks for the help - Is there a deterministic way to determine what token my test would produce  (I assume it has to be deterministic) - Therefore allowing me to add one more test for the case of Same token, but locked?

**Comment by Fraser-Cumming** [comment]
Also I've noticed another weird problem that seems rather difficult to understand why this wouldn't work.

```
@Service
public class LockedExampleService {

    public void test(UUID id) {
        testLocking(id);
    }

    @JdbcLocked(expression = "#p0", storeId = "test_command_lock")
    public void testLocking(UUID id) {
        System.out.println("Test locking called with id " + id);
    }
}
```

```
    @Test
    //Doesn't work - calls test() which in turn calls my locked method.
    public void testLock() {
        UUID id = UUID.randomUUID();
        jdbcTemplate.update(CREATE_LOCK_QUERY, id, UUID.randomUUID(), Timestamp.from(Instant.now().plus(1, ChronoUnit.DAYS)));
        lockedExampleService.test(id);
    }
    
    @Test
    //Does work - calling the locked method directly
    public void testLockDirect() {
        UUID id = UUID.randomUUID();
        jdbcTemplate.update(CREATE_LOCK_QUERY, id, UUID.randomUUID(), Timestamp.from(Instant.now().plus(1, ChronoUnit.DAYS)));
        lockedExampleService.testLocking(id);
    }
```

If I call the locked method directly from the test the locking works, however if I call from another method which in turn calls the locked method it doesn't lock. Is there another weirdity in spring going on here?

**Comment by alturkovic** [comment]
Yes, the thing you have encountered is called [Self Invocation](https://stackoverflow.com/questions/23931698/spring-transactional-annotation-self-invocation).

The tokens are generated using a generic [supplier](https://github.com/alturkovic/distributed-lock/blob/master/distributed-lock-core/src/main/java/com/github/alturkovic/lock/AbstractSimpleLock.java#L38). If you want to use a deterministic token, override the current [JdbcLock](https://github.com/alturkovic/distributed-lock/blob/master/distributed-lock-jdbc/src/main/java/com/github/alturkovic/lock/jdbc/configuration/JdbcDistributedLockConfiguration.java) with your own. Simply create the following bean instead:

```java
@Bean
  public Lock simpleJdbcLock(final JdbcLockSingleKeyService jdbcLockSingleKeyService) {
    return new SimpleJdbcLock(() -> "myToken", jdbcLockSingleKeyService);
}
```

**Comment by Fraser-Cumming** [comment]
Thank you for the help, much appreciated.
