### ISSUE TITLE
About throwing option added in recent PR

### ISSUE THREAD

**Issue by hsshee** [alturkovic/distributed-lock#46]
I was wondering why line 65 in the code block below is returning null instead of returning the result of the invocation.proceed() call.

https://github.com/alturkovic/distributed-lock/blob/06efe84229b5349c77fd553e3e263014bb5f8765/distributed-lock-core/src/main/java/com/github/alturkovic/lock/advice/LockMethodInterceptor.java#L62-L68

I assumed that the `throwing` option was added to call the target method rather than throwing a `DistributedLockException` when there's a problem with redis or a network failure, but seeing that it returns null, I'm wondering if my assumption is wrong.

**Comment by alturkovic** [comment]
Take a look here: https://github.com/alturkovic/distributed-lock/issues/41.

The idea is to allow users choose `null` over an exception when acquiring a lock fails. This is particularly useful for `@Scheduled` tasks which usually return `void` type anyway. Most scheduling frameworks do not expect exceptions to be thrown from scheduled jobs.

The code block you listed allows exactly that. When your annotated function is called, the library will throw a `DistributedLockException` by default. However, if you use `throwing=false`, no exception will be thrown, the invocation will simply return `null` instead.
