### ISSUE TITLE
Mongo distributed lock - expireAt not used

### ISSUE THREAD

**Issue by lgaudez** [alturkovic/distributed-lock#5]
Hi, 

Thanks for the implementation but I am wondering when the "expired" lock document are removed in the following code https://github.com/alturkovic/distributed-lock/blob/c21e364136979258b6976efde4015b6103ff2d02/distributed-lock-mongo/src/main/java/com/github/alturkovic/lock/mongo/impl/SimpleMongoLock.java#L76

Am I missing something?

By the way, I think I'll adapt your implementation to use ReactiveMongoTemplate.

**Comment by lgaudez** [comment]
Oh damn, I missed that note!! I let you know for the reactive. Thank a lot, you can close the non issue :)

**Comment by lgaudez** [comment]
@alturkovic After reading documentation on TTL indexes (https://docs.mongodb.com/manual/core/index-ttl/), this part scared me : 

> Timing of the Delete Operation
> When you build a TTL index in the background, the TTL thread can begin deleting documents while the index is building. If you build a TTL index in the foreground, MongoDB begins removing expired documents as soon as the index finishes building.
> 
> The TTL index does not guarantee that expired data will be deleted immediately upon expiration. There may be a delay between the time a document expires and the time that MongoDB removes the document from the database.
> 
> The background task that removes expired documents runs every 60 seconds. As a result, documents may remain in a collection during the period between the expiration of the document and the running of the background task.
> 
> Because the duration of the removal operation depends on the workload of your mongod instance, expired data may exist for some time beyond the 60 second period between runs of the background task.

That means Mongo does not guarantee deletion after expireAt. If I am trying to acquire a lock on a specific key already locked, the document containing the lock even if expired would not be deleted and I won't be able to acquired the lock. 

We may need to be defensive and remove existing document with same key and expireAt < now() ? What do you think about it?

Thanks

**Comment by alturkovic** [comment]
The implementation uses `expireAt` rather than `expireAfterSeconds` as explained [here](https://docs.mongodb.com/manual/tutorial/expire-data/#expire-documents-at-a-specific-clock-time). I do not believe this is the same behavior and that records should be deleted at the specified time.

TBH, I haven't used MongoDB much myself, so this implementation might be flawed. If you could write a test case and reproduce inconsistencies I could look into this, but for now, I think this works as intended.

**Comment by lgaudez** [comment]
Thanks for the quick answer. It seems alright according to the doc you pointed to me. Thanks
