### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by AndreaAdvanon** [alturkovic/distributed-lock#7]
Is there an easy way to test annotated methods in `SpringBootTest`?

I'd like to disable `distributed-lock` entirely, I tried with:
```kotlin
@Profile("!test")
@Configuration
@EnableJdbcDistributedLock
class DistributedLockConfiguration
```

But this fails at runtime

**Comment by AndreaAdvanon** [comment]
```kotlin
@RunWith(SpringRunner::class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Sql(
    statements = [
    """
    CREATE TABLE IF NOT EXISTS lock (
        id        BIGINT AUTO_INCREMENT PRIMARY KEY,
        lock_key  VARCHAR(255) UNIQUE ,
        token     VARCHAR(255),
        expireAt  TIMESTAMP
    );
    """
])
```

this works, could the SQL be avoided?

**Comment by alturkovic** [comment]
What exactly are you trying to test? Have you considered mocks? The library itself has tests you can take a look at. If you want to write additional Jdbc tests, you will have to create the table (there is another way of creating it, take a look at the Jdbc tests).

**Comment by AndreaAdvanon** [comment]
You mean using a script? Yes this is what I ended up doing.
I easily mocked the manual lock but how could I do it for the `@JdbcLock` annotated methods?
Would be nice to be able to just disable the lock during tests imo.

**Comment by AndreaAdvanon** [comment]
Ah, I know what the problem is:

```
@Service
class DistributedLockService(@Qualifier("simpleJdbcLock") private val distributedLock: Lock) {

    // This value is the default table name for simpleJdbcLock
    private val STORE_ID = "lock"

    fun <T> runLocked(key: Any, expiration: Long = Duration.ofSeconds(1).toMillis(), block: () -> T): T {
        val token = acquireLock(key, expiration)
        val result = block()
        releaseLock(key, token)
        return result
    }

    fun acquireLock(key: Any, expiration: Long): String =
        distributedLock.acquire(mutableListOf(key.toString()), STORE_ID, expiration)

    fun releaseLock(key: Any, token: String) {
        distributedLock.release(mutableListOf(key.toString()), token, STORE_ID)
    }
}
```

**Comment by alturkovic** [comment]
Oh yeah, disabling `LockBeanPostProcessor` will not help for manual invocations ofcourse :)

And only now I have noticed that I should have rearranged the parameters of the `acquire` and `release` methods :/

**Comment by alturkovic** [comment]
> I guess I cannot have both the annotation and the manual locks at the same time if I want to disable it. Or I should provide another DistributedLockService for tests.

Exactly, you should write a different `DistributedLockService` OR mock the `distributedLock` if you are using the locks manually.

**Comment by AndreaAdvanon** [comment]
Yes, I mocked `distributedLock` in unit test and created the actual tables on integration tests.
Thanks you!
